import fs from 'fs';
import path from 'path';
import { INITIAL_RECIPES } from '../src/data/recipes.js';

const DEST_DIR = path.join(process.cwd(), 'public', 'images', 'recipes');
const REGISTRY_FILE = path.join(process.cwd(), 'src', 'data', 'recipeImageRegistry.ts');

if (!fs.existsSync(DEST_DIR)) {
  fs.mkdirSync(DEST_DIR, { recursive: true });
}

// Load existing registry if it exists to avoid redownloading
let registry: Record<string, string> = {};
if (fs.existsSync(REGISTRY_FILE)) {
    try {
        const content = fs.readFileSync(REGISTRY_FILE, 'utf8');
        const match = content.match(/export const RECIPE_IMAGE_REGISTRY: Record<string, string> = ({[\s\S]*?});/);
        if (match && match[1]) {
            registry = JSON.parse(match[1]);
        }
    } catch(e) {}
}

const CONCURRENCY = 5;

async function downloadImage(url: string, destPath: string): Promise<boolean> {
    try {
        const res = await fetch(url);
        if (!res.ok) return false;
        const buffer = await res.arrayBuffer();
        fs.writeFileSync(destPath, Buffer.from(buffer));
        return true;
    } catch (e) {
        return false;
    }
}

function getPrompt(recipe: any) {
    const title = recipe.title;
    const ingredients = recipe.ingredients?.slice(0, 5).join(', ') || '';
    const desc = recipe.description || '';
    return `Professional macro food photography of authentic ${title}. ${desc} Key ingredients visible: ${ingredients}. High resolution, appetizing, beautifully plated, top-down view.`;
}

async function processBatch(recipes: any[], batchIndex: number, batchSize: number) {
    console.log(`\n--- Processing Batch ${batchIndex + 1} (Size: ${recipes.length}) ---`);
    const promises = recipes.map(async (recipe) => {
        const destFilename = `${recipe.id}.jpg`;
        const destPath = path.join(DEST_DIR, destFilename);
        const publicUrl = `/images/recipes/${destFilename}`;

        // Skip if already exists and is in registry
        if (fs.existsSync(destPath) && registry[recipe.id] === publicUrl) {
            const stats = fs.statSync(destPath);
            if (stats.size > 10000) {
                 return { id: recipe.id, url: publicUrl, cached: true };
            }
        }

        const prompt = getPrompt(recipe);
        // Using a deterministic seed
        let seed = 0;
        for (let i = 0; i < recipe.id.length; i++) {
            seed = (seed << 5) - seed + recipe.id.charCodeAt(i);
            seed |= 0;
        }
        seed = Math.abs(seed) % 10000;

        const aiUrl = `https://image.pollinations.ai/prompt/${encodeURIComponent(prompt)}?width=800&height=600&nologo=true&seed=${seed}`;
        
        let success = false;
        for (let attempt = 1; attempt <= 3; attempt++) {
            success = await downloadImage(aiUrl, destPath);
            if (success) {
                const stats = fs.statSync(destPath);
                if (stats.size > 10000) break; // Valid image
                success = false;
            }
            await new Promise(r => setTimeout(r, 1000));
        }

        if (success) {
            return { id: recipe.id, url: publicUrl, cached: false };
        } else {
            console.error(`  [FAILED] ${recipe.title} (${recipe.id})`);
            return { id: recipe.id, url: null, cached: false };
        }
    });

    const results = await Promise.all(promises);
    let newCount = 0;
    
    for (const res of results) {
        if (res.url) {
            registry[res.id] = res.url;
            if (!res.cached) newCount++;
        }
    }
    
    console.log(`Batch ${batchIndex + 1} complete. Downloaded ${newCount} new images. Cached: ${results.length - newCount}`);
    
    // Save registry
    const outputCode = `// AUTO-GENERATED FILE. DO NOT EDIT DIRECTLY.
// Generated by scripts/generate-recipe-images.ts

export const RECIPE_IMAGE_REGISTRY: Record<string, string> = ${JSON.stringify(registry, null, 2)};
`;
    fs.writeFileSync(REGISTRY_FILE, outputCode);
}

async function run() {
    console.log(`Starting image generation for ${INITIAL_RECIPES.length} recipes...`);
    const batchSize = 20;
    
    for (let i = 0; i < INITIAL_RECIPES.length; i += batchSize) {
        const batch = INITIAL_RECIPES.slice(i, i + batchSize);
        await processBatch(batch, i / batchSize, batchSize);
    }
    
    console.log("\nAll batches completed!");
}

run();
